export const GET_FEATURE_PRODUCTS_REQUEST = 'GET_FEATURE_PRODUCTS_REQUEST';

export const GET_FEATURE_PRODUCTS_SUCCESS = 'GET_FEATURE_PRODUCTS_SUCCESS';

export const GET_FEATURE_PRODUCTS_FAIL = 'GET_FEATURE_PRODUCTS_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";