export const GET_NEW_ARRIVALS_REQUEST = 'GET_NEW_ARRIVALS_REQUEST';

export const GET_NEW_ARRIVALS_SUCCESS = 'GET_NEW_ARRIVALS_SUCCESS';

export const GET_NEW_ARRIVALS_FAIL = 'GET_NEW_ARRIVALS_FAIL';

export const GET_PRICE_ASC_REQUEST = 'GET_PRICE_ASC_REQUEST';

export const GET_PRICE_ASC_SUCCESS = 'GET_PRICE_ASC_SUCCESS';

export const GET_PRICE_ASC_FAIL = 'GET_PRICE_ASC_FAIL';

export const GET_PRICE_DESC_REQUEST = 'GET_PRICE_DESC_REQUEST';

export const GET_PRICE_DESC_SUCCESS = 'GET_PRICE_DESC_SUCCESS';

export const GET_PRICE_DESC_FAIL = 'GET_PRICE_DESC_FAIL';

export const CLEAR_ERRORS = "CLEAR_ERRORS";